name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy-to-aws
      run: |
        aws configure set default.region $AWS_REGION
        aws configure set default.output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        aws cloudformation deploy --template-file cloudformation.yaml --stack-name evann-stack --no-fail-on-empty-changeset
        aws cloudformation deploy --template-file ecs-task.yaml --stack-name ecsV2-task --parameter-overrides ImageName=docker.io/evanndeb/ssc:sha-$(git rev-parse --short HEAD) --no-fail-on-empty-changeset
    - uses: minchao/cfn-nag-action@master
      with:
        args: '--input-path cf-all.yaml'
