name: cnf-nag

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
    - uses: minchao/cfn-nag-action@master
      with:
        args: '--input-path cf-all.yaml'
