name: Cnf-nag 

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: build-push
    - uses: minchao/cfn-nag-action@master
      with:
       args: '--input-path template.yaml'
